/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dabFrontend_fftHandler */

#ifndef _Included_utils_fftHandler
#define _Included_utils_fftHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_fftHandler
 * Method:    fftWrapper
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_utils_fftHandler_fftWrapper
  (JNIEnv *, jobject, jint);

/*
 * Class:     utils_fftHandler
 * Method:    do_FFT
 * Signature: (J[FI)V
 */
JNIEXPORT void JNICALL Java_utils_fftHandler_do_1FFT
  (JNIEnv *, jobject, jlong, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
