/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_AACDecoder */

#ifndef _Included_utils_AACDecoder
#define _Included_utils_AACDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_AACDecoder
 * Method:    aacReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_utils_AACDecoder_aacReset
  (JNIEnv *, jobject);

/*
 * Class:     utils_AACDecoder
 * Method:    aacInitialize
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_utils_AACDecoder_aacInitialize
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     utils_AACDecoder
 * Method:    aacDecode
 * Signature: ([BII[I)I
 */
JNIEXPORT jint JNICALL Java_utils_AACDecoder_aacDecode
  (JNIEnv *, jobject, jbyteArray, jint, jint, jintArray);

/*
 * Class:     utils_AACDecoder
 * Method:    aacFetchData
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_utils_AACDecoder_aacFetchData
  (JNIEnv *, jobject, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
