/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class package_Model_MP2_Processor */

#ifndef _Included_package_Model_MP2_Processor
#define _Included_package_Model_MP2_Processor
#ifdef __cplusplus
extern "C" {
#endif
#undef package_Model_MP2_Processor_KJMP2_MAX_FRAME_SIZE
#define package_Model_MP2_Processor_KJMP2_MAX_FRAME_SIZE 1440L
#undef package_Model_MP2_Processor_KJMP2_SAMPLES_PER_FRAME
#define package_Model_MP2_Processor_KJMP2_SAMPLES_PER_FRAME 1152L
/*
 * Class:     package_Model_MP2_Processor
 * Method:    mp2decodeFrame
 * Signature: (J[B[S)Z
 */
JNIEXPORT jboolean JNICALL Java_package_1Model_MP2_1Processor_mp2decodeFrame
  (JNIEnv *, jobject, jlong, jbyteArray, jshortArray);

/*
 * Class:     package_Model_MP2_Processor
 * Method:    init_mp2lib
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_package_1Model_MP2_1Processor_init_1mp2lib
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
