/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_ViterbiHandler */

#ifndef _Included_utils_ViterbiHandler
#define _Included_utils_ViterbiHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_ViterbiHandler
 * Method:    deconvolve
 * Signature: (J[I[B)V
 */
JNIEXPORT void JNICALL Java_utils_ViterbiHandler_deconvolve
  (JNIEnv *, jobject, jlong, jintArray, jbyteArray);

/*
 * Class:     utils_ViterbiHandler
 * Method:    initViterbi
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_utils_ViterbiHandler_initViterbi
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
